const sozlerListesi = [
    "Ölüm beklemez, sen de bekleme!",
    "Sevap gizlidir, gösterme!",
    "Allah'a koş, dünyaya değil!",
    "Kalbini temizle, dünya zaten kirli!",
    "Bugünlük yaşıyorsun, yarınlık değilsin!",
    "Vakit kaybolmaz, sen kaybolursun!",
    "Ölüm erken değil, hayat geç!",
    "Akıllı insan kendini sorgular!",
    "Yarın kılarım diyenin, bugün kıldık namazını.",
    "İnsan dünya ile kirlenir, secde ile temizlenir!",
    "Ruhun aç, farkında değilsin!",
    "Günah büyümez, sen büyütürsün!",
    "Ruhun karardığında secdeye dön!",
    "Dert büyümez, sen büyütürsün!",
    "Kendini değil, yükünü bırak!",
    "Sözünü değil, kalbini düzelt!",
    "Derdin çoksa, Rabbine yakınsın!",
    "Sana verilen sana yeter!",
    "Hesap günü uzak değil!",
    "Ölmek değil, hesaba çekilmek zor!",
    "Hiçbir şey senin değil; nefes bile!",
    "Gidiş var, dönüş yok!",
    "Bugün varsın yarın yok! Hazırlan!",
    "Allah varken çaresizlik yok!",
    "Şükret! Hayat değişir.",
    "Telaş etme, kalıcı değiliz!",
    "Dünyayı değil, hatanı düzelt!",
    "Ahiret büyük, dünya kısa!",
    "Fâni olana bağlanma!",
    "Ahireti unutturuyorlar! Aç gözünü!",
    "Dün geçti yarın var mı? Gençliğine güvenme ölen hep ihtiyar mı?",
    "Allah'tan geldik, Allah'a döneceğiz!",
    "Unutma; Allah'ın dediği olur!",
    "Dağ dağa kavuşmaz, insan Allah'a kavuşur!",
    "Sabret - Şükret - Dua et!",
    "Yaradan dost olduktan sonra, kulu düşman olsa ne yazar!",
    "Allah'a dön!",
    "En büyük yalnızlık; Rabbini unutmak!",
    "Allah'a ağlayan herkes güldü!",
    "Dünya kandırır, ahiret uyandırır!"
];
